"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export const languages = [
  { code: "en", label: "English", nativeLabel: "ENG", dir: "ltr" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी", dir: "ltr" },
  { code: "pa", label: "Punjabi", nativeLabel: "ਪੰਜਾਬੀ", dir: "ltr" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்", dir: "ltr" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు", dir: "ltr" },
  { code: "bho", label: "Bhojpuri", nativeLabel: "भोजपुरी", dir: "ltr" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी", dir: "ltr" },
  { code: "bn", label: "Bengali", nativeLabel: "বাংলা", dir: "ltr" },
  { code: "ur", label: "Urdu", nativeLabel: "اردو", dir: "rtl" },
];

const translations = {
  en: {
    "brand.tagline": "Guidance, live and personal",
    "nav.astrologers": "Astrologers",
    "nav.horoscope": "Horoscope",
    "nav.kundli": "Kundli",
    "nav.compatibility": "Compatibility",
    "search.placeholder": "Search astrologers, topics...",
    "auth.login": "Login",
    "auth.loginTitle": "Welcome Back to",
    "auth.astrologerLogin": "Astrologer Login",
    "auth.loginSubtitle": "Enter your username and password to login",
    "auth.astrologerLoginSubtitle": "Sign in to open your consultations, clients, and public profile.",
    "auth.username": "Username",
    "auth.password": "Password",
    "auth.enterUsername": "Enter username",
    "auth.enterPassword": "Enter password",
    "auth.forgotPassword": "Forgot Password?",
    "auth.sendingResetLink": "Sending reset link...",
    "auth.forgotPasswordSent": "If an account with that email exists, a password reset link has been sent.",
    "auth.forgotPasswordFailed": "Unable to send reset link. Please try again.",
    "auth.signingIn": "Signing in...",
    "auth.openAstrologerProfile": "Open Astrologer Profile",
    "auth.noAccount": "Don't have an account?",
    "auth.usernameRequired": "Username is required",
    "auth.passwordRequired": "Password is required",
    "auth.passwordMin": "Password must be at least 6 characters",
    "auth.loginFailed": "Login failed. Please try again.",
    "auth.loginSuccessful": "Login successful",
    "auth.clientDetected": "Client account detected. Opening your client dashboard.",
    "auth.registerNow": "Register Now",
    "auth.profileDetails": "Profile Details",
    "auth.logout": "Logout",
    "auth.loggingOut": "Logging out...",
    "auth.welcomeBack": "Welcome back",
    "hero.dailyReading": "Your Daily Reading",
    "hero.cosmicGuidance": "Cosmic Guidance",
    "hero.goodMorning": "Good Morning",
    "hero.goodAfternoon": "Good Afternoon",
    "hero.goodEvening": "Good Evening",
    "hero.explorer": "Explorer",
    "hero.loggedInText": "The stars have messages for you today!",
    "hero.guestText": "Discover what the universe has in store for you.",
    "hero.walletBalance": "Wallet Balance",
    "hero.addMoney": "+ Add Money",
    "hero.todayEnergy": "Today's Energy",
    "hero.positiveZone": "Positive Zone",
    "hero.energyText": "You're radiating strong cosmic energy today.",
    "hero.energyCta": "Keep the momentum going!",
    "hero.todayGlance": "Today at a Glance",
    "hero.morning": "Morning",
    "hero.afternoon": "Afternoon",
    "hero.evening": "Evening",
    "hero.focus": "Focus",
    "hero.execute": "Execute",
    "hero.reflect": "Reflect",
    "quick.title": "Quick Actions",
    "quick.viewAll": "View All",
    "quick.talk": "Talk to Astrologer",
    "quick.horoscope": "Daily Horoscope",
    "quick.kundli": "Kundli Report",
    "quick.compatibility": "Compatibility",
    "planet.title": "Planetary Highlights",
    "planet.venus": "Venus",
    "planet.mercury": "Mercury",
    "planet.mars": "Mars",
    "planet.jupiter": "Jupiter",
    "planet.strong": "Strong",
    "planet.weak": "Weak",
    "planet.loveHarmony": "Love & Harmony",
    "planet.avoidMiscommunication": "Avoid Miscommunication",
    "planet.highEnergy": "High Energy",
    "planet.growthAbundance": "Growth & Abundance",
    "categories.love": "Love & Relationships",
    "categories.career": "Career & Finance",
    "categories.health": "Health & Wellness",
    "categories.growth": "Personal Growth",
    "categories.explore": "Explore",
    "life.title": "Guidance for Every Part of Your Life",
    "life.subtitle": "Explore insights tailored to your journey",
    "life.loveDesc": "Understand your emotional path",
    "life.careerDesc": "Plan your next big move",
    "life.healthDesc": "Balance your mind & body",
    "life.growthDesc": "Unlock your true potential",
    "sidebar.wallet": "Wallet Balance",
    "sidebar.dailyHoroscope": "Daily Horoscope",
    "sidebar.viewAll": "View All",
    "sidebar.aries": "Aries",
    "sidebar.love": "Love",
    "sidebar.career": "Career",
    "sidebar.health": "Health",
    "sidebar.loveText": "Good time for honesty",
    "sidebar.careerText": "New opportunities coming",
    "sidebar.healthText": "Take care of your sleep",
    "sidebar.suggestedQuestions": "Suggested Questions",
    "sidebar.questionJob": "Will I get a new job?",
    "sidebar.questionMarriage": "Is marriage in my destiny?",
    "sidebar.questionFocus": "What should I focus on?",
    "sidebar.upcomingSession": "Upcoming Session",
    "sidebar.joinSession": "Join Session",
    "sidebar.theme": "Theme",
    "sidebar.firstChatFree": "First Chat Free",
    "sidebar.claimNow": "Claim Now",
    "sidebar.clientQueue": "Client Queue",
    "sidebar.openClients": "Open Clients",
    "sidebar.firstChatText": "Get 5 minutes FREE with your first astrologer.",
    "sidebar.clientQueueText": "Review your assigned clients and active sessions.",
    "astro.top": "Top Astrologers",
    "astro.filters": "Filters",
    "astro.resetFilters": "Reset Filters",
    "astro.category": "Category",
    "astro.language": "Language",
    "astro.location": "Location",
    "astro.experience": "Experience",
    "astro.allExperience": "All Experience",
    "astro.years0to5": "0 - 5 Years",
    "astro.years6to10": "6 - 10 Years",
    "astro.years11plus": "11+ Years",
    "astro.yearsExperience": "Years Experience",
    "astro.chat": "Chat",
    "astro.call": "Call",
    "astro.viewProfile": "View Profile",
    "astro.viewMore": "View More",
    "astro.empty": "No astrologers match your filters.",
    "common.all": "All",
    "register.registration": "Registration",
    "register.chooseType": "Choose Registration Type",
    "register.startPath": "Start with the path that fits you.",
    "register.pathSubtitle": "Create a client account for consultations or apply as an astrologer for verification.",
    "register.switchBefore": "You can switch back here before creating an account.",
    "register.astrologer": "Sign Up as Astrologer",
    "register.astrologerDesc": "Submit your professional profile and documents for verification.",
    "register.client": "Sign Up as Client",
    "register.clientDesc": "Create your account and begin booking consultations.",
    "register.alreadyAccount": "Already have an account?",
    "register.clientRegistration": "Client Registration",
    "register.createAccountTitle": "Create your ApsaraAstro account.",
    "register.createAccountDesc": "Join the platform, save your profile, and connect with guidance when you need it.",
    "register.clientSignup": "Client Signup",
    "register.welcomeTo": "Welcome to",
    "register.createJourney": "Create your account and start your journey.",
    "register.changeType": "Change type",
    "register.firstName": "First Name",
    "register.middleName": "Middle Name",
    "register.lastName": "Last Name",
    "register.email": "Email",
    "register.mobile": "Mobile",
    "register.dateOfBirth": "Date of Birth",
    "register.birthPlace": "Birth Place",
    "register.fullAddress": "Full Address",
    "register.gender": "Gender",
    "register.selectGender": "Select Gender",
    "register.male": "Male",
    "register.female": "Female",
    "register.other": "Other",
    "register.confirmPassword": "Confirm Password",
    "register.show": "Show",
    "register.hide": "Hide",
    "register.notRobot": "I'm not a robot",
    "register.createAccount": "Create Account",
    "register.creating": "Creating...",
    "register.required": "{field} is required",
    "register.validEmail": "Enter valid email address",
    "register.phoneDigits": "Phone must be 10 digits",
    "register.passwordsMismatch": "Passwords do not match",
    "register.validDob": "Enter valid date of birth",
    "register.success": "Registration Successful",
    "register.failed": "Registration failed",
    "register.somethingWrong": "Something went wrong",
    "signup.accountSetup": "Account Setup",
    "signup.title": "Sign Up to",
    "signup.subtitle": "Enter your username and password to receive an OTP for verification.",
    "signup.createFor": "Create account for",
    "signup.clientSubtitle": "Create your client login first, then verify the OTP on the registration page.",
    "signup.astrologerSubtitle": "Create your astrologer login first, then verify the OTP during registration.",
    "signup.otp": "OTP",
    "signup.otpHelper": "Enter the OTP sent by the registration API.",
    "signup.validOtp": "OTP must be 4 to 8 digits",
    "signup.detailsSaved": "An OTP is sent to the given email, please enter it for verification.",
    "signup.creating": "Sending OTP...",
    "signup.failed": "Signup failed. Please try again.",
    "signup.continueClient": "Continue to Client Registration",
    "signup.continueAstrologer": "Continue to Astrologer Registration",
    "modal.loginRequired": "Login Required",
    "modal.loginMessage": "Please login to access this feature and continue your cosmic journey.",
    "modal.cancel": "Cancel",
    "chat.title": "Chat",
    "chat.placeholder": "Type your question...",
    "chat.send": "Send",
    "chat.hello": "Hello! How can I guide you today?",
    "chat.reply": "I see positive energy around this. Stay focused ✨",
    "notifications.title": "Notifications",
    "notifications.horoscopeReady": "Horoscope ready",
    "notifications.newMessage": "New message",
    "astroReg.title": "Complete your verification profile with confidence.",
    "astroReg.subtitle": "Share your profile and optional documents in one compact application flow.",
    "astroReg.back": "Back to registration options",
    "astroReg.progress": "Application progress",
    "astroReg.currentStep": "Current step",
    "astroReg.stepsTitle": "Verification Steps",
    "astroReg.stepsSubtitle": "Four compact sections keep the application easy to complete.",
    "astroReg.step": "Step",
    "astroReg.continue": "Continue",
    "astroReg.backButton": "Back",
    "astroReg.submit": "Submit Application",
    "astroReg.submitting": "Submitting...",
    "astroReg.tab1": "Personal & Professional Information",
    "astroReg.tab2": "Identity Verification",
    "astroReg.tab3": "Education & Certification",
    "astroReg.tab4": "Account & Declaration",
    "astroReg.desc1": "Profile basics, expertise, languages, and consultation modes.",
    "astroReg.desc2": "Optional Aadhar document upload.",
    "astroReg.desc3": "Higher education, certificates, experience letter, and profile photo.",
    "astroReg.desc4": "Optional account password and final declaration.",
    "astroReg.fullName": "Full Name",
    "astroReg.mobileNumber": "Mobile Number",
    "astroReg.emailAddress": "Email Address",
    "astroReg.pincode": "Pincode",
    "astroReg.city": "City",
    "astroReg.state": "State",
    "astroReg.languagesKnown": "Languages Known",
    "astroReg.fetchingLocation": "Fetching city and state...",
    "astroReg.yearsExperience": "Years of Experience",
    "astroReg.consultationModes": "Consultation Modes",
    "astroReg.expertise": "Expertise",
    "astroReg.aboutYourself": "About Yourself",
    "astroReg.aadharFront": "Aadhar Card Front",
    "astroReg.aadharBack": "Aadhar Card Back",
    "astroReg.panCard": "PAN Card",
    "astroReg.addressProof": "Address Proof (Passport / Voter ID / Driving License / Utility Bill)",
    "astroReg.educationalCertificate": "Higher Education Degree / Diploma Upload",
    "astroReg.certificateDocuments": "Certificate Documents (up to 3)",
    "astroReg.astrologyCertificate": "Astrology Course Certificate",
    "astroReg.numerologyCertificate": "Numerology Certificate",
    "astroReg.vastuCertificate": "Vastu Certificate",
    "astroReg.palmistryCertificate": "Palmistry Certificate",
    "astroReg.graphologyCertificate": "Graphology Certificate",
    "astroReg.reikiCertificate": "Reiki Certificate",
    "astroReg.tarotCertificate": "Tarot Certificate",
    "astroReg.supportingPrompt": "Upload any one or more supporting documents.",
    "astroReg.experienceLetter": "Experience Letter",
    "astroReg.mediaProof": "Media / Publication Proof",
    "astroReg.clientTestimonials": "Client Testimonials",
    "astroReg.passportPhoto": "Passport Size Photo",
    "astroReg.accountHolderName": "Account Holder Name",
    "astroReg.bankName": "Bank Name",
    "astroReg.accountNumber": "Account Number",
    "astroReg.ifscCode": "IFSC Code",
    "astroReg.branchName": "Branch Name",
    "astroReg.upiId": "UPI ID (Optional)",
    "astroReg.declaration": "I hereby declare that all information provided is true and I have no criminal record.",
    "astroReg.digitalSignature": "Full Name as Digital Signature",
    "astroReg.date": "Date",
    "astroReg.allowed": "Allowed formats: JPG, PNG, PDF",
    "astroReg.maxFiles": "Maximum {count} files",
    "astroReg.requiredToast": "Please complete the required details",
    "astroReg.fixFields": "Please fix the highlighted fields before submitting",
    "astroReg.invalidFile": "Only JPG, PNG, and PDF files are allowed",
    "astroReg.supportingRequired": "Upload at least one supporting document",
    "astroReg.declarationRequired": "Declaration is required",
    "astroReg.success": "Your application has been submitted successfully and is pending verification.",
    "astroReg.failed": "Astrologer registration failed",
    "astroReg.unableSubmit": "Unable to submit application. Please try again.",
    "menu.home": "Home",
    "menu.exploreAstrologers": "Explore Astrologers",
    "menu.chatSessions": "Chat / Sessions",
    "menu.kundliReports": "Kundli / Reports",
    "menu.dailyHoroscope": "Daily Horoscope",
    "menu.compatibility": "Compatibility",
    "menu.askUniverse": "Ask the Universe (AI)",
    "menu.voiceGuidance": "Voice Guidance",
    "menu.myActivity": "My Activity",
    "menu.savedInsights": "Saved Insights",
    "menu.walletPayments": "Wallet & Payments",
    "menu.profileSettings": "Profile & Settings",
    "menu.ourProfile": "Our Profile",
    "menu.losuGrid": "Lo Shu Grid",
    "menu.ourClients": "Our Clients",
  },
  hi: {
    "brand.tagline": "लाइव और व्यक्तिगत मार्गदर्शन",
    "nav.astrologers": "ज्योतिषी",
    "nav.horoscope": "राशिफल",
    "nav.kundli": "कुंडली",
    "nav.compatibility": "मिलान",
    "search.placeholder": "ज्योतिषी या विषय खोजें...",
    "auth.login": "लॉगिन",
    "auth.loginTitle": "फिर से स्वागत है",
    "auth.astrologerLogin": "ज्योतिषी लॉगिन",
    "auth.loginSubtitle": "लॉगिन करने के लिए यूज़रनेम और पासवर्ड डालें",
    "auth.astrologerLoginSubtitle": "अपनी consultations, clients और public profile खोलने के लिए साइन इन करें।",
    "auth.username": "यूज़रनेम",
    "auth.password": "पासवर्ड",
    "auth.enterUsername": "यूज़रनेम डालें",
    "auth.enterPassword": "पासवर्ड डालें",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.signingIn": "साइन इन हो रहा है...",
    "auth.openAstrologerProfile": "ज्योतिषी प्रोफ़ाइल खोलें",
    "auth.noAccount": "अकाउंट नहीं है?",
    "auth.usernameRequired": "यूज़रनेम आवश्यक है",
    "auth.passwordRequired": "पासवर्ड आवश्यक है",
    "auth.passwordMin": "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
    "auth.loginFailed": "लॉगिन विफल। कृपया फिर कोशिश करें।",
    "auth.loginSuccessful": "लॉगिन सफल",
    "auth.clientDetected": "क्लाइंट अकाउंट मिला। आपका क्लाइंट डैशबोर्ड खोला जा रहा है।",
    "auth.registerNow": "रजिस्टर करें",
    "auth.profileDetails": "प्रोफ़ाइल विवरण",
    "auth.logout": "लॉगआउट",
    "auth.loggingOut": "लॉगआउट हो रहा है...",
    "auth.welcomeBack": "फिर से स्वागत है",
    "hero.dailyReading": "आपका दैनिक मार्गदर्शन",
    "hero.cosmicGuidance": "कॉस्मिक मार्गदर्शन",
    "hero.goodMorning": "सुप्रभात",
    "hero.goodAfternoon": "नमस्कार",
    "hero.goodEvening": "शुभ संध्या",
    "hero.explorer": "एक्सप्लोरर",
    "hero.loggedInText": "आज सितारों के पास आपके लिए संदेश हैं!",
    "hero.guestText": "जानें ब्रह्मांड ने आपके लिए क्या रखा है।",
    "hero.walletBalance": "वॉलेट बैलेंस",
    "hero.addMoney": "+ पैसा जोड़ें",
    "hero.todayEnergy": "आज की ऊर्जा",
    "hero.positiveZone": "सकारात्मक क्षेत्र",
    "hero.energyText": "आज आपकी कॉस्मिक ऊर्जा मजबूत है।",
    "hero.energyCta": "इसी गति को बनाए रखें!",
    "hero.todayGlance": "आज की झलक",
    "hero.morning": "सुबह",
    "hero.afternoon": "दोपहर",
    "hero.evening": "शाम",
    "hero.focus": "फोकस",
    "hero.execute": "कार्रवाई",
    "hero.reflect": "चिंतन",
    "quick.title": "त्वरित सेवाएं",
    "quick.viewAll": "सभी देखें",
    "quick.talk": "ज्योतिषी से बात करें",
    "quick.horoscope": "दैनिक राशिफल",
    "quick.kundli": "कुंडली रिपोर्ट",
    "quick.compatibility": "मिलान",
    "planet.title": "ग्रहों की स्थिति",
    "planet.venus": "शुक्र",
    "planet.mercury": "बुध",
    "planet.mars": "मंगल",
    "planet.jupiter": "बृहस्पति",
    "planet.strong": "मजबूत",
    "planet.weak": "कमजोर",
    "planet.loveHarmony": "प्रेम और सामंजस्य",
    "planet.avoidMiscommunication": "गलतफहमी से बचें",
    "planet.highEnergy": "उच्च ऊर्जा",
    "planet.growthAbundance": "विकास और समृद्धि",
    "categories.love": "प्रेम और रिश्ते",
    "categories.career": "करियर और वित्त",
    "categories.health": "स्वास्थ्य और वेलनेस",
    "categories.growth": "व्यक्तिगत विकास",
    "categories.explore": "देखें",
    "life.title": "जीवन के हर हिस्से के लिए मार्गदर्शन",
    "life.subtitle": "अपनी यात्रा के अनुसार insights देखें",
    "life.loveDesc": "अपने भावनात्मक रास्ते को समझें",
    "life.careerDesc": "अपना अगला बड़ा कदम योजना बनाएं",
    "life.healthDesc": "मन और शरीर का संतुलन रखें",
    "life.growthDesc": "अपनी सच्ची क्षमता पहचानें",
    "sidebar.wallet": "वॉलेट बैलेंस",
    "sidebar.dailyHoroscope": "दैनिक राशिफल",
    "sidebar.viewAll": "सभी देखें",
    "sidebar.aries": "मेष",
    "sidebar.love": "प्रेम",
    "sidebar.career": "करियर",
    "sidebar.health": "स्वास्थ्य",
    "sidebar.loveText": "ईमानदारी के लिए अच्छा समय",
    "sidebar.careerText": "नए अवसर आ रहे हैं",
    "sidebar.healthText": "नींद का ध्यान रखें",
    "sidebar.suggestedQuestions": "सुझाए गए प्रश्न",
    "sidebar.questionJob": "क्या मुझे नई नौकरी मिलेगी?",
    "sidebar.questionMarriage": "क्या मेरी शादी भाग्य में है?",
    "sidebar.questionFocus": "मुझे किस पर ध्यान देना चाहिए?",
    "sidebar.upcomingSession": "आगामी सेशन",
    "sidebar.joinSession": "सेशन जॉइन करें",
    "sidebar.theme": "थीम",
    "sidebar.firstChatFree": "पहली चैट मुफ्त",
    "sidebar.claimNow": "अभी लें",
    "sidebar.clientQueue": "क्लाइंट कतार",
    "sidebar.openClients": "क्लाइंट खोलें",
    "sidebar.firstChatText": "पहले ज्योतिषी के साथ 5 मिनट मुफ्त पाएं।",
    "sidebar.clientQueueText": "अपने क्लाइंट और सक्रिय सेशन देखें।",
    "astro.top": "टॉप ज्योतिषी",
    "astro.filters": "फ़िल्टर",
    "astro.resetFilters": "फ़िल्टर रीसेट",
    "astro.category": "श्रेणी",
    "astro.language": "भाषा",
    "astro.location": "स्थान",
    "astro.experience": "अनुभव",
    "astro.allExperience": "सभी अनुभव",
    "astro.years0to5": "0 - 5 वर्ष",
    "astro.years6to10": "6 - 10 वर्ष",
    "astro.years11plus": "11+ वर्ष",
    "astro.yearsExperience": "वर्ष अनुभव",
    "astro.chat": "चैट",
    "astro.call": "कॉल",
    "astro.viewProfile": "प्रोफ़ाइल देखें",
    "astro.viewMore": "और देखें",
    "astro.empty": "इन फ़िल्टर से कोई ज्योतिषी नहीं मिला।",
    "common.all": "सभी",
    "register.registration": "रजिस्ट्रेशन",
    "register.chooseType": "रजिस्ट्रेशन प्रकार चुनें",
    "register.startPath": "अपने लिए सही रास्ते से शुरुआत करें।",
    "register.pathSubtitle": "Consultations के लिए client account बनाएं या verification के लिए astrologer के रूप में apply करें।",
    "register.switchBefore": "अकाउंट बनाने से पहले आप यहां वापस आ सकते हैं।",
    "register.astrologer": "ज्योतिषी के रूप में साइन अप",
    "register.astrologerDesc": "Verification के लिए अपनी professional profile और documents जमा करें।",
    "register.client": "क्लाइंट के रूप में साइन अप",
    "register.clientDesc": "अपना अकाउंट बनाएं और consultations बुक करना शुरू करें।",
    "register.alreadyAccount": "पहले से अकाउंट है?",
    "register.clientRegistration": "क्लाइंट रजिस्ट्रेशन",
    "register.createAccountTitle": "अपना ApsaraAstro अकाउंट बनाएं।",
    "register.createAccountDesc": "Platform से जुड़ें, profile save करें और जरूरत पड़ने पर guidance से connect करें।",
    "register.clientSignup": "क्लाइंट साइनअप",
    "register.welcomeTo": "स्वागत है",
    "register.createJourney": "अपना अकाउंट बनाएं और यात्रा शुरू करें।",
    "register.changeType": "प्रकार बदलें",
    "register.firstName": "पहला नाम",
    "register.middleName": "मध्य नाम",
    "register.lastName": "अंतिम नाम",
    "register.email": "ईमेल",
    "register.mobile": "मोबाइल",
    "register.dateOfBirth": "जन्म तिथि",
    "register.birthPlace": "जन्म स्थान",
    "register.fullAddress": "पूरा पता",
    "register.gender": "लिंग",
    "register.selectGender": "लिंग चुनें",
    "register.male": "पुरुष",
    "register.female": "महिला",
    "register.other": "अन्य",
    "register.confirmPassword": "पासवर्ड पुष्टि",
    "register.show": "दिखाएं",
    "register.hide": "छिपाएं",
    "register.notRobot": "मैं रोबोट नहीं हूं",
    "register.createAccount": "अकाउंट बनाएं",
    "register.creating": "बन रहा है...",
    "register.required": "{field} आवश्यक है",
    "register.validEmail": "सही ईमेल डालें",
    "register.phoneDigits": "फोन 10 अंकों का होना चाहिए",
    "register.passwordsMismatch": "पासवर्ड मेल नहीं खाते",
    "register.validDob": "सही जन्म तिथि डालें",
    "register.success": "रजिस्ट्रेशन सफल",
    "register.failed": "रजिस्ट्रेशन विफल",
    "register.somethingWrong": "कुछ गलत हुआ",
    "modal.loginRequired": "लॉगिन आवश्यक",
    "modal.loginMessage": "इस सुविधा को उपयोग करने और अपनी cosmic journey जारी रखने के लिए login करें।",
    "modal.cancel": "रद्द करें",
    "chat.title": "चैट",
    "chat.placeholder": "अपना प्रश्न लिखें...",
    "chat.send": "भेजें",
    "chat.hello": "नमस्ते! मैं आज आपका कैसे मार्गदर्शन कर सकता/सकती हूं?",
    "chat.reply": "इसके आसपास सकारात्मक ऊर्जा दिख रही है। ध्यान बनाए रखें ✨",
    "notifications.title": "सूचनाएं",
    "notifications.horoscopeReady": "राशिफल तैयार है",
    "notifications.newMessage": "नया संदेश",
    "astroReg.title": "अपनी verification profile आत्मविश्वास से पूरी करें।",
    "astroReg.subtitle": "अपनी profile और optional documents एक compact application flow में भरें।",
    "astroReg.back": "रजिस्ट्रेशन विकल्पों पर वापस",
    "astroReg.progress": "Application progress",
    "astroReg.currentStep": "वर्तमान step",
    "astroReg.stepsTitle": "Verification Steps",
    "astroReg.stepsSubtitle": "चार compact sections application को आसान बनाते हैं।",
    "astroReg.step": "Step",
    "astroReg.continue": "जारी रखें",
    "astroReg.backButton": "वापस",
    "astroReg.submit": "Application Submit करें",
    "astroReg.submitting": "Submit हो रहा है...",
    "astroReg.tab1": "Personal & Professional Information",
    "astroReg.tab2": "Identity Verification",
    "astroReg.tab3": "Education & Certification",
    "astroReg.tab4": "Account & Declaration",
    "astroReg.desc1": "Profile basics, expertise, languages और consultation modes.",
    "astroReg.desc2": "Optional Aadhar document upload.",
    "astroReg.desc3": "Higher education, certificates, experience letter और profile photo.",
    "astroReg.desc4": "Optional account password और final declaration.",
    "astroReg.fullName": "पूरा नाम",
    "astroReg.mobileNumber": "मोबाइल नंबर",
    "astroReg.emailAddress": "ईमेल पता",
    "astroReg.pincode": "पिनकोड",
    "astroReg.city": "शहर",
    "astroReg.state": "राज्य",
    "astroReg.languagesKnown": "ज्ञात भाषाएं",
    "astroReg.fetchingLocation": "City और state fetch हो रहे हैं...",
    "astroReg.yearsExperience": "अनुभव के वर्ष",
    "astroReg.consultationModes": "Consultation Modes",
    "astroReg.expertise": "विशेषज्ञता",
    "astroReg.aboutYourself": "अपने बारे में",
    "astroReg.aadharFront": "आधार कार्ड Front",
    "astroReg.aadharBack": "आधार कार्ड Back",
    "astroReg.panCard": "PAN कार्ड",
    "astroReg.addressProof": "Address Proof",
    "astroReg.educationalCertificate": "Higher Education Degree / Diploma Upload",
    "astroReg.certificateDocuments": "Certificate Documents (up to 3)",
    "astroReg.astrologyCertificate": "Astrology Course Certificate",
    "astroReg.numerologyCertificate": "Numerology Certificate",
    "astroReg.vastuCertificate": "Vastu Certificate",
    "astroReg.palmistryCertificate": "Palmistry Certificate",
    "astroReg.graphologyCertificate": "Graphology Certificate",
    "astroReg.reikiCertificate": "Reiki Certificate",
    "astroReg.tarotCertificate": "Tarot Certificate",
    "astroReg.supportingPrompt": "कोई एक या अधिक supporting documents upload करें।",
    "astroReg.experienceLetter": "Experience Letter",
    "astroReg.mediaProof": "Media / Publication Proof",
    "astroReg.clientTestimonials": "Client Testimonials",
    "astroReg.passportPhoto": "Passport Size Photo",
    "astroReg.accountHolderName": "Account Holder Name",
    "astroReg.bankName": "Bank Name",
    "astroReg.accountNumber": "Account Number",
    "astroReg.ifscCode": "IFSC Code",
    "astroReg.branchName": "Branch Name",
    "astroReg.upiId": "UPI ID (Optional)",
    "astroReg.declaration": "मैं घोषणा करता/करती हूं कि दी गई सभी जानकारी सत्य है और मेरा कोई criminal record नहीं है।",
    "astroReg.digitalSignature": "Digital Signature के रूप में पूरा नाम",
    "astroReg.date": "तिथि",
    "astroReg.allowed": "Allowed formats: JPG, PNG, PDF",
    "astroReg.maxFiles": "Maximum {count} files",
    "astroReg.requiredToast": "कृपया आवश्यक details पूरी करें",
    "astroReg.fixFields": "Submit करने से पहले highlighted fields ठीक करें",
    "astroReg.invalidFile": "केवल JPG, PNG और PDF files allowed हैं",
    "astroReg.supportingRequired": "कम से कम एक supporting document upload करें",
    "astroReg.declarationRequired": "Declaration आवश्यक है",
    "astroReg.success": "आपकी application सफलतापूर्वक submit हो गई है और verification pending है।",
    "astroReg.failed": "Astrologer registration failed",
    "astroReg.unableSubmit": "Application submit नहीं हो सकी। कृपया फिर कोशिश करें।",
    "menu.home": "होम",
    "menu.exploreAstrologers": "ज्योतिषी देखें",
    "menu.chatSessions": "चैट / सेशन",
    "menu.kundliReports": "कुंडली / रिपोर्ट",
    "menu.dailyHoroscope": "दैनिक राशिफल",
    "menu.compatibility": "मिलान",
    "menu.askUniverse": "ब्रह्मांड से पूछें (AI)",
    "menu.voiceGuidance": "वॉइस मार्गदर्शन",
    "menu.myActivity": "मेरी गतिविधि",
    "menu.savedInsights": "सेव किए insights",
    "menu.walletPayments": "वॉलेट और भुगतान",
    "menu.profileSettings": "प्रोफ़ाइल और सेटिंग्स",
    "menu.ourProfile": "हमारी प्रोफ़ाइल",
    "menu.losuGrid": "लो शू ग्रिड",
    "menu.ourClients": "हमारे क्लाइंट",
  },
};

const partialTranslations = {
  pa: {
    "brand.tagline": "ਲਾਈਵ ਅਤੇ ਨਿੱਜੀ ਮਾਰਗਦਰਸ਼ਨ",
    "nav.astrologers": "ਜੋਤਿਸ਼ੀ",
    "nav.horoscope": "ਰਾਸ਼ੀਫਲ",
    "nav.kundli": "ਕੁੰਡਲੀ",
    "nav.compatibility": "ਮਿਲਾਪ",
    "search.placeholder": "ਜੋਤਿਸ਼ੀ ਜਾਂ ਵਿਸ਼ੇ ਖੋਜੋ...",
    "auth.login": "ਲਾਗਇਨ",
    "auth.registerNow": "ਰਜਿਸਟਰ ਕਰੋ",
    "quick.title": "ਤੁਰੰਤ ਸੇਵਾਵਾਂ",
    "quick.talk": "ਜੋਤਿਸ਼ੀ ਨਾਲ ਗੱਲ ਕਰੋ",
    "quick.horoscope": "ਰੋਜ਼ਾਨਾ ਰਾਸ਼ੀਫਲ",
    "quick.kundli": "ਕੁੰਡਲੀ ਰਿਪੋਰਟ",
    "quick.compatibility": "ਮਿਲਾਪ",
    "astro.top": "ਚੋਟੀ ਦੇ ਜੋਤਿਸ਼ੀ",
  },
  ta: {
    "brand.tagline": "நேரடி மற்றும் தனிப்பட்ட வழிகாட்டல்",
    "nav.astrologers": "ஜோதிடர்கள்",
    "nav.horoscope": "ராசிபலன்",
    "nav.kundli": "ஜாதகம்",
    "nav.compatibility": "பொருத்தம்",
    "search.placeholder": "ஜோதிடர்கள், தலைப்புகள் தேடுங்கள்...",
    "auth.login": "உள்நுழை",
    "auth.registerNow": "பதிவு செய்",
    "quick.title": "விரைவு சேவைகள்",
    "quick.talk": "ஜோதிடருடன் பேசுங்கள்",
    "quick.horoscope": "தினசரி ராசிபலன்",
    "quick.kundli": "ஜாதக அறிக்கை",
    "quick.compatibility": "பொருத்தம்",
    "astro.top": "சிறந்த ஜோதிடர்கள்",
  },
  te: {
    "brand.tagline": "లైవ్ మరియు వ్యక్తిగత మార్గదర్శనం",
    "nav.astrologers": "జ్యోతిష్కులు",
    "nav.horoscope": "రాశిఫలం",
    "nav.kundli": "జాతకం",
    "nav.compatibility": "అనుకూలత",
    "search.placeholder": "జ్యోతిష్కులు, విషయాలు వెతకండి...",
    "auth.login": "లాగిన్",
    "auth.registerNow": "నమోదు",
    "quick.title": "త్వరిత సేవలు",
    "quick.talk": "జ్యోతిష్కుడితో మాట్లాడండి",
    "quick.horoscope": "రోజువారీ రాశిఫలం",
    "quick.kundli": "జాతక నివేదిక",
    "quick.compatibility": "అనుకూలత",
    "astro.top": "అగ్ర జ్యోతిష్కులు",
  },
  bho: {
    "brand.tagline": "लाइव अउर निजी मार्गदर्शन",
    "nav.astrologers": "ज्योतिषी",
    "nav.horoscope": "राशिफल",
    "nav.kundli": "कुंडली",
    "nav.compatibility": "मिलान",
    "search.placeholder": "ज्योतिषी आ विषय खोजीं...",
    "auth.login": "लॉगिन",
    "auth.registerNow": "रजिस्टर करीं",
    "quick.title": "जल्दी सेवा",
    "quick.talk": "ज्योतिषी से बात करीं",
    "quick.horoscope": "रोज के राशिफल",
    "quick.kundli": "कुंडली रिपोर्ट",
    "quick.compatibility": "मिलान",
    "astro.top": "टॉप ज्योतिषी",
  },
  mr: {
    "brand.tagline": "थेट आणि वैयक्तिक मार्गदर्शन",
    "nav.astrologers": "ज्योतिषी",
    "nav.horoscope": "राशिभविष्य",
    "nav.kundli": "कुंडली",
    "nav.compatibility": "जुळवणी",
    "search.placeholder": "ज्योतिषी किंवा विषय शोधा...",
    "auth.login": "लॉगिन",
    "auth.registerNow": "नोंदणी करा",
    "quick.title": "त्वरित सेवा",
    "quick.talk": "ज्योतिषींशी बोला",
    "quick.horoscope": "दैनिक राशिभविष्य",
    "quick.kundli": "कुंडली रिपोर्ट",
    "quick.compatibility": "जुळवणी",
    "astro.top": "टॉप ज्योतिषी",
  },
  bn: {
    "brand.tagline": "লাইভ এবং ব্যক্তিগত নির্দেশনা",
    "nav.astrologers": "জ্যোতিষী",
    "nav.horoscope": "রাশিফল",
    "nav.kundli": "কুণ্ডলী",
    "nav.compatibility": "ম্যাচিং",
    "search.placeholder": "জ্যোতিষী বা বিষয় খুঁজুন...",
    "auth.login": "লগইন",
    "auth.registerNow": "রেজিস্টার",
    "quick.title": "দ্রুত পরিষেবা",
    "quick.talk": "জ্যোতিষীর সাথে কথা বলুন",
    "quick.horoscope": "দৈনিক রাশিফল",
    "quick.kundli": "কুণ্ডলী রিপোর্ট",
    "quick.compatibility": "ম্যাচিং",
    "astro.top": "সেরা জ্যোতিষী",
  },
  ur: {
    "brand.tagline": "براہ راست اور ذاتی رہنمائی",
    "nav.astrologers": "نجومی",
    "nav.horoscope": "زائچہ",
    "nav.kundli": "کنڈلی",
    "nav.compatibility": "مطابقت",
    "search.placeholder": "نجومی یا موضوع تلاش کریں...",
    "auth.login": "لاگ ان",
    "auth.registerNow": "رجسٹر کریں",
    "quick.title": "فوری خدمات",
    "quick.talk": "نجومی سے بات کریں",
    "quick.horoscope": "روزانہ زائچہ",
    "quick.kundli": "کنڈلی رپورٹ",
    "quick.compatibility": "مطابقت",
    "astro.top": "بہترین نجومی",
  },
};

const extendedTranslations = {
  pa: {
    "auth.profileDetails": "ਪ੍ਰੋਫ਼ਾਈਲ ਵੇਰਵੇ",
    "auth.logout": "ਲਾਗਆਉਟ",
    "auth.loggingOut": "ਲਾਗਆਉਟ ਹੋ ਰਿਹਾ ਹੈ...",
    "auth.welcomeBack": "ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ",
    "hero.dailyReading": "ਤੁਹਾਡੀ ਰੋਜ਼ਾਨਾ ਰੀਡਿੰਗ",
    "hero.cosmicGuidance": "ਕੌਸਮਿਕ ਮਾਰਗਦਰਸ਼ਨ",
    "hero.goodMorning": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ",
    "hero.goodAfternoon": "ਨਮਸਕਾਰ",
    "hero.goodEvening": "ਸ਼ੁਭ ਸ਼ਾਮ",
    "hero.explorer": "ਐਕਸਪਲੋਰਰ",
    "hero.loggedInText": "ਅੱਜ ਤਾਰਿਆਂ ਕੋਲ ਤੁਹਾਡੇ ਲਈ ਸੁਨੇਹੇ ਹਨ!",
    "hero.guestText": "ਜਾਣੋ ਬ੍ਰਹਿਮੰਡ ਨੇ ਤੁਹਾਡੇ ਲਈ ਕੀ ਰੱਖਿਆ ਹੈ।",
    "hero.walletBalance": "ਵਾਲਿਟ ਬੈਲੈਂਸ",
    "hero.addMoney": "+ ਪੈਸੇ ਜੋੜੋ",
    "hero.todayEnergy": "ਅੱਜ ਦੀ ਊਰਜਾ",
    "hero.positiveZone": "ਸਕਾਰਾਤਮਕ ਜ਼ੋਨ",
    "hero.energyText": "ਅੱਜ ਤੁਹਾਡੀ ਕੌਸਮਿਕ ਊਰਜਾ ਮਜ਼ਬੂਤ ਹੈ।",
    "hero.energyCta": "ਇਹ ਗਤੀ ਬਣਾਈ ਰੱਖੋ!",
    "hero.todayGlance": "ਅੱਜ ਦੀ ਝਲਕ",
    "hero.morning": "ਸਵੇਰ",
    "hero.afternoon": "ਦੁਪਹਿਰ",
    "hero.evening": "ਸ਼ਾਮ",
    "hero.focus": "ਧਿਆਨ",
    "hero.execute": "ਕੰਮ",
    "hero.reflect": "ਵਿਚਾਰ",
    "quick.viewAll": "ਸਭ ਵੇਖੋ",
    "planet.title": "ਗ੍ਰਹਿ ਹਾਈਲਾਈਟਸ",
    "categories.love": "ਪਿਆਰ ਅਤੇ ਰਿਸ਼ਤੇ",
    "categories.career": "ਕਰੀਅਰ ਅਤੇ ਵਿੱਤ",
    "categories.health": "ਸਿਹਤ ਅਤੇ ਵੈਲਨੈੱਸ",
    "categories.growth": "ਨਿੱਜੀ ਵਿਕਾਸ",
    "categories.explore": "ਖੋਲ੍ਹੋ",
    "life.title": "ਜੀਵਨ ਦੇ ਹਰ ਹਿੱਸੇ ਲਈ ਮਾਰਗਦਰਸ਼ਨ",
    "life.subtitle": "ਆਪਣੀ ਯਾਤਰਾ ਮੁਤਾਬਕ ਸੁਝਾਅ ਵੇਖੋ",
    "life.loveDesc": "ਆਪਣਾ ਭਾਵਨਾਤਮਕ ਰਾਹ ਸਮਝੋ",
    "life.careerDesc": "ਆਪਣਾ ਅਗਲਾ ਵੱਡਾ ਕਦਮ ਯੋਜਨਾ ਬਣਾਓ",
    "life.healthDesc": "ਮਨ ਅਤੇ ਸਰੀਰ ਸੰਤੁਲਿਤ ਰੱਖੋ",
    "life.growthDesc": "ਆਪਣੀ ਅਸਲ ਸਮਰੱਥਾ ਖੋਲ੍ਹੋ",
    "common.all": "ਸਭ",
    "astro.filters": "ਫਿਲਟਰ",
    "astro.resetFilters": "ਫਿਲਟਰ ਰੀਸੈੱਟ",
    "astro.yearsExperience": "ਸਾਲ ਅਨੁਭਵ",
    "astro.chat": "ਚੈਟ",
    "astro.call": "ਕਾਲ",
    "astro.viewProfile": "ਪ੍ਰੋਫ਼ਾਈਲ ਵੇਖੋ",
    "astro.viewMore": "ਹੋਰ ਵੇਖੋ",
    "menu.home": "ਹੋਮ",
    "menu.exploreAstrologers": "ਜੋਤਿਸ਼ੀ ਵੇਖੋ",
    "menu.chatSessions": "ਚੈਟ / ਸੈਸ਼ਨ",
    "menu.kundliReports": "ਕੁੰਡਲੀ / ਰਿਪੋਰਟ",
    "menu.dailyHoroscope": "ਰੋਜ਼ਾਨਾ ਰਾਸ਼ੀਫਲ",
    "menu.myActivity": "ਮੇਰੀ ਗਤੀਵਿਧੀ",
    "menu.walletPayments": "ਵਾਲਿਟ ਅਤੇ ਭੁਗਤਾਨ",
    "menu.profileSettings": "ਪ੍ਰੋਫ਼ਾਈਲ ਅਤੇ ਸੈਟਿੰਗਾਂ",
    "auth.loginTitle": "ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ",
    "auth.astrologerLogin": "ਜੋਤਿਸ਼ੀ ਲਾਗਇਨ",
    "auth.loginSubtitle": "ਲਾਗਇਨ ਲਈ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਭਰੋ",
    "auth.username": "ਯੂਜ਼ਰਨੇਮ",
    "auth.password": "ਪਾਸਵਰਡ",
    "auth.enterUsername": "ਯੂਜ਼ਰਨੇਮ ਭਰੋ",
    "auth.enterPassword": "ਪਾਸਵਰਡ ਭਰੋ",
    "auth.forgotPassword": "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    "auth.signingIn": "ਸਾਇਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
    "auth.noAccount": "ਅਕਾਊਂਟ ਨਹੀਂ ਹੈ?",
    "register.registration": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
    "register.chooseType": "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਕਿਸਮ ਚੁਣੋ",
    "register.astrologer": "ਜੋਤਿਸ਼ੀ ਵਜੋਂ ਸਾਇਨ ਅਪ",
    "register.client": "ਕਲਾਇੰਟ ਵਜੋਂ ਸਾਇਨ ਅਪ",
    "register.alreadyAccount": "ਪਹਿਲਾਂ ਹੀ ਅਕਾਊਂਟ ਹੈ?",
    "register.firstName": "ਪਹਿਲਾ ਨਾਮ",
    "register.lastName": "ਆਖਰੀ ਨਾਮ",
    "register.email": "ਈਮੇਲ",
    "register.mobile": "ਮੋਬਾਈਲ",
    "register.gender": "ਲਿੰਗ",
    "register.passwordsMismatch": "ਪਾਸਵਰਡ ਨਹੀਂ ਮਿਲਦੇ",
    "register.createAccount": "ਅਕਾਊਂਟ ਬਣਾਓ",
  },
  ta: {
    "auth.profileDetails": "சுயவிவர விவரங்கள்",
    "auth.logout": "வெளியேறு",
    "auth.loggingOut": "வெளியேறுகிறது...",
    "auth.welcomeBack": "மீண்டும் வரவேற்கிறோம்",
    "hero.dailyReading": "உங்கள் தினசரி வாசிப்பு",
    "hero.cosmicGuidance": "பிரபஞ்ச வழிகாட்டல்",
    "hero.goodMorning": "காலை வணக்கம்",
    "hero.goodAfternoon": "மதிய வணக்கம்",
    "hero.goodEvening": "மாலை வணக்கம்",
    "hero.explorer": "ஆராய்பவர்",
    "hero.loggedInText": "இன்று நட்சத்திரங்கள் உங்களுக்குச் செய்தி கொண்டுள்ளன!",
    "hero.guestText": "பிரபஞ்சம் உங்களுக்கு என்ன வைத்துள்ளது என்பதை அறியுங்கள்.",
    "hero.walletBalance": "வாலட் இருப்பு",
    "hero.addMoney": "+ பணம் சேர்க்க",
    "hero.todayEnergy": "இன்றைய ஆற்றல்",
    "hero.positiveZone": "நேர்மறை நிலை",
    "hero.energyText": "இன்று உங்கள் பிரபஞ்ச ஆற்றல் வலுவாக உள்ளது.",
    "hero.energyCta": "இந்த வேகத்தை தொடருங்கள்!",
    "hero.todayGlance": "இன்றைய பார்வை",
    "hero.morning": "காலை",
    "hero.afternoon": "மதியம்",
    "hero.evening": "மாலை",
    "hero.focus": "கவனம்",
    "hero.execute": "செயல்",
    "hero.reflect": "சிந்தனை",
    "quick.viewAll": "அனைத்தும்",
    "planet.title": "கிரக சிறப்புகள்",
    "categories.love": "காதல் & உறவுகள்",
    "categories.career": "வேலை & நிதி",
    "categories.health": "ஆரோக்கியம்",
    "categories.growth": "தனிப்பட்ட வளர்ச்சி",
    "categories.explore": "ஆராய்க",
    "life.title": "வாழ்க்கையின் ஒவ்வொரு பகுதிக்கும் வழிகாட்டல்",
    "life.subtitle": "உங்கள் பயணத்திற்கு ஏற்ற தகவல்கள்",
    "life.loveDesc": "உங்கள் உணர்ச்சி பாதையை புரிந்துகொள்ளுங்கள்",
    "life.careerDesc": "அடுத்த பெரிய முடிவை திட்டமிடுங்கள்",
    "life.healthDesc": "மனம் மற்றும் உடலை சமநிலைப்படுத்துங்கள்",
    "life.growthDesc": "உங்கள் உண்மையான திறனை திறக்குங்கள்",
    "common.all": "அனைத்தும்",
    "astro.filters": "வடிகட்டி",
    "astro.resetFilters": "வடிகட்டியை நீக்கு",
    "astro.yearsExperience": "ஆண்டு அனுபவம்",
    "astro.chat": "அரட்டை",
    "astro.call": "அழை",
    "astro.viewProfile": "சுயவிவரம்",
    "astro.viewMore": "மேலும்",
    "menu.home": "முகப்பு",
    "menu.exploreAstrologers": "ஜோதிடர்கள்",
    "menu.chatSessions": "அரட்டை / அமர்வுகள்",
    "menu.kundliReports": "ஜாதகம் / அறிக்கை",
    "menu.dailyHoroscope": "தினசரி ராசிபலன்",
    "menu.myActivity": "என் செயல்பாடு",
    "menu.walletPayments": "வாலட் & கட்டணம்",
    "menu.profileSettings": "சுயவிவரம் & அமைப்புகள்",
    "auth.loginTitle": "மீண்டும் வரவேற்கிறோம்",
    "auth.astrologerLogin": "ஜோதிடர் உள்நுழைவு",
    "auth.loginSubtitle": "உள்நுழைய பயனர்பெயர் மற்றும் கடவுச்சொல் உள்ளிடவும்",
    "auth.username": "பயனர்பெயர்",
    "auth.password": "கடவுச்சொல்",
    "auth.enterUsername": "பயனர்பெயர் உள்ளிடவும்",
    "auth.enterPassword": "கடவுச்சொல் உள்ளிடவும்",
    "auth.forgotPassword": "கடவுச்சொல் மறந்துவிட்டதா?",
    "auth.signingIn": "உள்நுழைகிறது...",
    "auth.noAccount": "கணக்கு இல்லையா?",
    "register.registration": "பதிவு",
    "register.chooseType": "பதிவு வகையைத் தேர்ந்தெடுக்கவும்",
    "register.astrologer": "ஜோதிடராக பதிவு",
    "register.client": "வாடிக்கையாளராக பதிவு",
    "register.alreadyAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "register.firstName": "முதல் பெயர்",
    "register.lastName": "கடைசி பெயர்",
    "register.email": "மின்னஞ்சல்",
    "register.mobile": "மொபைல்",
    "register.gender": "பாலினம்",
    "register.passwordsMismatch": "கடவுச்சொற்கள் பொருந்தவில்லை",
    "register.createAccount": "கணக்கு உருவாக்கு",
  },
  te: {
    "auth.profileDetails": "ప్రొఫైల్ వివరాలు",
    "auth.logout": "లాగౌట్",
    "auth.loggingOut": "లాగౌట్ అవుతోంది...",
    "auth.welcomeBack": "మళ్లీ స్వాగతం",
    "hero.dailyReading": "మీ రోజువారీ రీడింగ్",
    "hero.cosmicGuidance": "కాస్మిక్ మార్గదర్శనం",
    "hero.goodMorning": "శుభోదయం",
    "hero.goodAfternoon": "శుభ మధ్యాహ్నం",
    "hero.goodEvening": "శుభ సాయంత్రం",
    "hero.explorer": "అన్వేషకుడు",
    "hero.loggedInText": "ఈ రోజు నక్షత్రాలు మీకు సందేశాలు కలిగి ఉన్నాయి!",
    "hero.guestText": "విశ్వం మీ కోసం ఏమి ఉంచిందో తెలుసుకోండి.",
    "hero.walletBalance": "వాలెట్ బ్యాలెన్స్",
    "hero.addMoney": "+ డబ్బు జోడించండి",
    "hero.todayEnergy": "ఈ రోజు శక్తి",
    "hero.positiveZone": "సానుకూల స్థితి",
    "hero.energyText": "ఈ రోజు మీ కాస్మిక్ శక్తి బలంగా ఉంది.",
    "hero.energyCta": "ఈ ఉత్సాహాన్ని కొనసాగించండి!",
    "hero.todayGlance": "ఈ రోజు ఒక చూపు",
    "hero.morning": "ఉదయం",
    "hero.afternoon": "మధ్యాహ్నం",
    "hero.evening": "సాయంత్రం",
    "hero.focus": "దృష్టి",
    "hero.execute": "చర్య",
    "hero.reflect": "ఆలోచన",
    "quick.viewAll": "అన్నీ చూడండి",
    "planet.title": "గ్రహాల ముఖ్యాంశాలు",
    "categories.love": "ప్రేమ & సంబంధాలు",
    "categories.career": "కెరీర్ & ఫైనాన్స్",
    "categories.health": "ఆరోగ్యం",
    "categories.growth": "వ్యక్తిగత అభివృద్ధి",
    "categories.explore": "చూడండి",
    "life.title": "జీవితంలోని ప్రతి భాగానికి మార్గదర్శనం",
    "life.subtitle": "మీ ప్రయాణానికి సరిపోయే సూచనలు",
    "life.loveDesc": "మీ భావోద్వేగ మార్గాన్ని అర్థం చేసుకోండి",
    "life.careerDesc": "మీ తదుపరి పెద్ద అడుగును ప్లాన్ చేయండి",
    "life.healthDesc": "మనసు మరియు శరీరాన్ని సమతుల్యం చేయండి",
    "life.growthDesc": "మీ నిజమైన సామర్థ్యాన్ని వెలికితీయండి",
    "common.all": "అన్నీ",
    "astro.filters": "ఫిల్టర్లు",
    "astro.resetFilters": "ఫిల్టర్లు రీసెట్",
    "astro.yearsExperience": "సంవత్సరాల అనుభవం",
    "astro.chat": "చాట్",
    "astro.call": "కాల్",
    "astro.viewProfile": "ప్రొఫైల్ చూడండి",
    "astro.viewMore": "మరిన్ని",
    "menu.home": "హోమ్",
    "menu.exploreAstrologers": "జ్యోతిష్కులు",
    "menu.chatSessions": "చాట్ / సెషన్లు",
    "menu.kundliReports": "జాతకం / రిపోర్టులు",
    "menu.dailyHoroscope": "రోజువారీ రాశిఫలం",
    "menu.myActivity": "నా కార్యాచరణ",
    "menu.walletPayments": "వాలెట్ & చెల్లింపులు",
    "menu.profileSettings": "ప్రొఫైల్ & సెట్టింగ్స్",
    "auth.loginTitle": "మళ్లీ స్వాగతం",
    "auth.astrologerLogin": "జ్యోతిష్కుడు లాగిన్",
    "auth.loginSubtitle": "లాగిన్ కోసం యూజర్‌నేమ్ మరియు పాస్‌వర్డ్ నమోదు చేయండి",
    "auth.username": "యూజర్‌నేమ్",
    "auth.password": "పాస్‌వర్డ్",
    "auth.enterUsername": "యూజర్‌నేమ్ నమోదు చేయండి",
    "auth.enterPassword": "పాస్‌వర్డ్ నమోదు చేయండి",
    "auth.forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "auth.signingIn": "సైన్ ఇన్ అవుతోంది...",
    "auth.noAccount": "ఖాతా లేదా?",
    "register.registration": "నమోదు",
    "register.chooseType": "నమోదు రకం ఎంచుకోండి",
    "register.astrologer": "జ్యోతిష్కుడిగా సైన్ అప్",
    "register.client": "క్లయింట్‌గా సైన్ అప్",
    "register.alreadyAccount": "ఇప్పటికే ఖాతా ఉందా?",
    "register.firstName": "మొదటి పేరు",
    "register.lastName": "చివరి పేరు",
    "register.email": "ఇమెయిల్",
    "register.mobile": "మొబైల్",
    "register.gender": "లింగం",
    "register.passwordsMismatch": "పాస్‌వర్డ్‌లు సరిపోలడం లేదు",
    "register.createAccount": "ఖాతా సృష్టించండి",
  },
  bho: {
    "auth.profileDetails": "प्रोफाइल विवरण",
    "auth.logout": "लॉगआउट",
    "auth.loggingOut": "लॉगआउट होत बा...",
    "auth.welcomeBack": "फेर से स्वागत बा",
    "hero.dailyReading": "रोज के रीडिंग",
    "hero.cosmicGuidance": "कॉस्मिक मार्गदर्शन",
    "hero.goodMorning": "सुप्रभात",
    "hero.goodAfternoon": "नमस्कार",
    "hero.goodEvening": "शुभ संझा",
    "hero.explorer": "खोजी",
    "hero.loggedInText": "आज तारा रउरा खातिर संदेश लेके आइल बा!",
    "hero.guestText": "जानीं ब्रह्मांड रउरा खातिर का रखले बा।",
    "hero.walletBalance": "वॉलेट बैलेंस",
    "hero.addMoney": "+ पइसा जोड़ीं",
    "hero.todayEnergy": "आज के ऊर्जा",
    "hero.positiveZone": "सकारात्मक जोन",
    "hero.energyText": "आज रउरा कॉस्मिक ऊर्जा मजबूत बा।",
    "hero.energyCta": "एही रफ्तार के बनवले रखीं!",
    "common.all": "सब",
    "categories.love": "प्यार आ रिश्ता",
    "categories.career": "करियर आ पइसा",
    "categories.health": "सेहत",
    "categories.growth": "निजी विकास",
    "categories.explore": "देखीं",
    "astro.filters": "फिल्टर",
    "astro.resetFilters": "फिल्टर हटाईं",
    "astro.yearsExperience": "साल अनुभव",
    "astro.chat": "चैट",
    "astro.call": "कॉल",
    "astro.viewProfile": "प्रोफाइल देखीं",
    "astro.viewMore": "आउर देखीं",
    "menu.home": "होम",
    "menu.exploreAstrologers": "ज्योतिषी देखीं",
    "menu.chatSessions": "चैट / सेशन",
    "menu.kundliReports": "कुंडली / रिपोर्ट",
    "menu.dailyHoroscope": "रोज के राशिफल",
    "auth.loginTitle": "फेर से स्वागत बा",
    "auth.astrologerLogin": "ज्योतिषी लॉगिन",
    "auth.loginSubtitle": "लॉगिन खातिर यूजरनेम आ पासवर्ड भरीं",
    "auth.username": "यूजरनेम",
    "auth.password": "पासवर्ड",
    "auth.enterUsername": "यूजरनेम भरीं",
    "auth.enterPassword": "पासवर्ड भरीं",
    "auth.forgotPassword": "पासवर्ड भुला गइल?",
    "auth.signingIn": "साइन इन होत बा...",
    "auth.noAccount": "अकाउंट नइखे?",
    "register.registration": "रजिस्ट्रेशन",
    "register.chooseType": "रजिस्ट्रेशन टाइप चुनीं",
    "register.astrologer": "ज्योतिषी बनके साइन अप",
    "register.client": "क्लाइंट बनके साइन अप",
    "register.alreadyAccount": "पहिले से अकाउंट बा?",
    "register.firstName": "पहिला नाम",
    "register.lastName": "आखिरी नाम",
    "register.email": "ईमेल",
    "register.mobile": "मोबाइल",
    "register.gender": "लिंग",
    "register.passwordsMismatch": "पासवर्ड मैच नइखे करत",
    "register.createAccount": "अकाउंट बनाईं",
  },
  mr: {
    "auth.profileDetails": "प्रोफाइल तपशील",
    "auth.logout": "लॉगआउट",
    "auth.loggingOut": "लॉगआउट होत आहे...",
    "auth.welcomeBack": "पुन्हा स्वागत",
    "hero.dailyReading": "तुमचे दैनिक वाचन",
    "hero.cosmicGuidance": "कॉस्मिक मार्गदर्शन",
    "hero.goodMorning": "सुप्रभात",
    "hero.goodAfternoon": "नमस्कार",
    "hero.goodEvening": "शुभ संध्याकाळ",
    "hero.explorer": "एक्सप्लोरर",
    "hero.loggedInText": "आज ताऱ्यांकडे तुमच्यासाठी संदेश आहेत!",
    "hero.guestText": "विश्वाने तुमच्यासाठी काय ठेवले आहे ते जाणून घ्या.",
    "hero.walletBalance": "वॉलेट बॅलन्स",
    "hero.addMoney": "+ पैसे जोडा",
    "hero.todayEnergy": "आजची ऊर्जा",
    "hero.positiveZone": "सकारात्मक झोन",
    "hero.energyText": "आज तुमची कॉस्मिक ऊर्जा मजबूत आहे.",
    "hero.energyCta": "ही गती कायम ठेवा!",
    "common.all": "सर्व",
    "categories.love": "प्रेम आणि नाती",
    "categories.career": "करिअर आणि वित्त",
    "categories.health": "आरोग्य",
    "categories.growth": "वैयक्तिक वाढ",
    "categories.explore": "पाहा",
    "astro.filters": "फिल्टर",
    "astro.resetFilters": "फिल्टर रीसेट",
    "astro.yearsExperience": "वर्षांचा अनुभव",
    "astro.chat": "चॅट",
    "astro.call": "कॉल",
    "astro.viewProfile": "प्रोफाइल पाहा",
    "astro.viewMore": "आणखी पाहा",
    "menu.home": "होम",
    "menu.exploreAstrologers": "ज्योतिषी पाहा",
    "menu.chatSessions": "चॅट / सेशन",
    "menu.kundliReports": "कुंडली / रिपोर्ट",
    "menu.dailyHoroscope": "दैनिक राशिभविष्य",
    "auth.loginTitle": "पुन्हा स्वागत",
    "auth.astrologerLogin": "ज्योतिषी लॉगिन",
    "auth.loginSubtitle": "लॉगिन करण्यासाठी यूजरनेम आणि पासवर्ड टाका",
    "auth.username": "यूजरनेम",
    "auth.password": "पासवर्ड",
    "auth.enterUsername": "यूजरनेम टाका",
    "auth.enterPassword": "पासवर्ड टाका",
    "auth.forgotPassword": "पासवर्ड विसरलात?",
    "auth.signingIn": "साइन इन होत आहे...",
    "auth.noAccount": "अकाउंट नाही?",
    "register.registration": "नोंदणी",
    "register.chooseType": "नोंदणी प्रकार निवडा",
    "register.astrologer": "ज्योतिषी म्हणून साइन अप",
    "register.client": "क्लायंट म्हणून साइन अप",
    "register.alreadyAccount": "आधीच अकाउंट आहे?",
    "register.firstName": "पहिले नाव",
    "register.lastName": "आडनाव",
    "register.email": "ईमेल",
    "register.mobile": "मोबाइल",
    "register.gender": "लिंग",
    "register.passwordsMismatch": "पासवर्ड जुळत नाहीत",
    "register.createAccount": "अकाउंट तयार करा",
  },
  bn: {
    "auth.profileDetails": "প্রোফাইল বিবরণ",
    "auth.logout": "লগআউট",
    "auth.loggingOut": "লগআউট হচ্ছে...",
    "auth.welcomeBack": "আবার স্বাগতম",
    "hero.dailyReading": "আপনার দৈনিক রিডিং",
    "hero.cosmicGuidance": "কসমিক নির্দেশনা",
    "hero.goodMorning": "সুপ্রভাত",
    "hero.goodAfternoon": "শুভ দুপুর",
    "hero.goodEvening": "শুভ সন্ধ্যা",
    "hero.explorer": "এক্সপ্লোরার",
    "hero.loggedInText": "আজ তারাদের কাছে আপনার জন্য বার্তা আছে!",
    "hero.guestText": "জানুন মহাবিশ্ব আপনার জন্য কী রেখেছে।",
    "hero.walletBalance": "ওয়ালেট ব্যালেন্স",
    "hero.addMoney": "+ টাকা যোগ করুন",
    "hero.todayEnergy": "আজকের শক্তি",
    "hero.positiveZone": "পজিটিভ জোন",
    "hero.energyText": "আজ আপনার কসমিক শক্তি প্রবল।",
    "hero.energyCta": "এই গতি বজায় রাখুন!",
    "common.all": "সব",
    "categories.love": "ভালোবাসা ও সম্পর্ক",
    "categories.career": "ক্যারিয়ার ও ফাইন্যান্স",
    "categories.health": "স্বাস্থ্য",
    "categories.growth": "ব্যক্তিগত উন্নতি",
    "categories.explore": "দেখুন",
    "astro.filters": "ফিল্টার",
    "astro.resetFilters": "ফিল্টার রিসেট",
    "astro.yearsExperience": "বছরের অভিজ্ঞতা",
    "astro.chat": "চ্যাট",
    "astro.call": "কল",
    "astro.viewProfile": "প্রোফাইল দেখুন",
    "astro.viewMore": "আরও দেখুন",
    "menu.home": "হোম",
    "menu.exploreAstrologers": "জ্যোতিষী দেখুন",
    "menu.chatSessions": "চ্যাট / সেশন",
    "menu.kundliReports": "কুণ্ডলী / রিপোর্ট",
    "menu.dailyHoroscope": "দৈনিক রাশিফল",
    "auth.loginTitle": "আবার স্বাগতম",
    "auth.astrologerLogin": "জ্যোতিষী লগইন",
    "auth.loginSubtitle": "লগইন করতে ইউজারনেম এবং পাসওয়ার্ড দিন",
    "auth.username": "ইউজারনেম",
    "auth.password": "পাসওয়ার্ড",
    "auth.enterUsername": "ইউজারনেম দিন",
    "auth.enterPassword": "পাসওয়ার্ড দিন",
    "auth.forgotPassword": "পাসওয়ার্ড ভুলে গেছেন?",
    "auth.signingIn": "সাইন ইন হচ্ছে...",
    "auth.noAccount": "অ্যাকাউন্ট নেই?",
    "register.registration": "রেজিস্ট্রেশন",
    "register.chooseType": "রেজিস্ট্রেশন ধরন বেছে নিন",
    "register.astrologer": "জ্যোতিষী হিসেবে সাইন আপ",
    "register.client": "ক্লায়েন্ট হিসেবে সাইন আপ",
    "register.alreadyAccount": "আগেই অ্যাকাউন্ট আছে?",
    "register.firstName": "নামের প্রথম অংশ",
    "register.lastName": "পদবি",
    "register.email": "ইমেল",
    "register.mobile": "মোবাইল",
    "register.gender": "লিঙ্গ",
    "register.passwordsMismatch": "পাসওয়ার্ড মিলছে না",
    "register.createAccount": "অ্যাকাউন্ট তৈরি করুন",
  },
  ur: {
    "auth.profileDetails": "پروفائل تفصیلات",
    "auth.logout": "لاگ آؤٹ",
    "auth.loggingOut": "لاگ آؤٹ ہو رہا ہے...",
    "auth.welcomeBack": "واپسی پر خوش آمدید",
    "hero.dailyReading": "آپ کی روزانہ ریڈنگ",
    "hero.cosmicGuidance": "کائناتی رہنمائی",
    "hero.goodMorning": "صبح بخیر",
    "hero.goodAfternoon": "دوپہر بخیر",
    "hero.goodEvening": "شام بخیر",
    "hero.explorer": "ایکسپلورر",
    "hero.loggedInText": "آج ستاروں کے پاس آپ کے لیے پیغام ہے!",
    "hero.guestText": "جانیں کائنات نے آپ کے لیے کیا رکھا ہے۔",
    "hero.walletBalance": "والٹ بیلنس",
    "hero.addMoney": "+ رقم شامل کریں",
    "hero.todayEnergy": "آج کی توانائی",
    "hero.positiveZone": "مثبت زون",
    "hero.energyText": "آج آپ کی کائناتی توانائی مضبوط ہے۔",
    "hero.energyCta": "یہ رفتار برقرار رکھیں!",
    "common.all": "سب",
    "categories.love": "محبت اور رشتے",
    "categories.career": "کیریئر اور مالیات",
    "categories.health": "صحت",
    "categories.growth": "ذاتی ترقی",
    "categories.explore": "دیکھیں",
    "astro.filters": "فلٹرز",
    "astro.resetFilters": "فلٹرز ری سیٹ",
    "astro.yearsExperience": "سال تجربہ",
    "astro.chat": "چیٹ",
    "astro.call": "کال",
    "astro.viewProfile": "پروفائل دیکھیں",
    "astro.viewMore": "مزید دیکھیں",
    "menu.home": "ہوم",
    "menu.exploreAstrologers": "نجومی دیکھیں",
    "menu.chatSessions": "چیٹ / سیشن",
    "menu.kundliReports": "کنڈلی / رپورٹس",
    "menu.dailyHoroscope": "روزانہ زائچہ",
    "auth.loginTitle": "واپسی پر خوش آمدید",
    "auth.astrologerLogin": "نجومی لاگ ان",
    "auth.loginSubtitle": "لاگ ان کے لیے یوزرنیم اور پاس ورڈ درج کریں",
    "auth.username": "یوزرنیم",
    "auth.password": "پاس ورڈ",
    "auth.enterUsername": "یوزرنیم درج کریں",
    "auth.enterPassword": "پاس ورڈ درج کریں",
    "auth.forgotPassword": "پاس ورڈ بھول گئے؟",
    "auth.signingIn": "سائن ان ہو رہا ہے...",
    "auth.noAccount": "اکاؤنٹ نہیں؟",
    "register.registration": "رجسٹریشن",
    "register.chooseType": "رجسٹریشن کی قسم منتخب کریں",
    "register.astrologer": "نجومی کے طور پر سائن اپ",
    "register.client": "کلائنٹ کے طور پر سائن اپ",
    "register.alreadyAccount": "پہلے سے اکاؤنٹ ہے؟",
    "register.firstName": "پہلا نام",
    "register.lastName": "آخری نام",
    "register.email": "ای میل",
    "register.mobile": "موبائل",
    "register.gender": "جنس",
    "register.passwordsMismatch": "پاس ورڈ مماثل نہیں",
    "register.createAccount": "اکاؤنٹ بنائیں",
  },
};

Object.entries(extendedTranslations).forEach(([code, values]) => {
  partialTranslations[code] = { ...partialTranslations[code], ...values };
});

Object.entries(partialTranslations).forEach(([code, values]) => {
  translations[code] = { ...translations.en, ...values };
});

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window === "undefined") {
      return "en";
    }

    const savedLanguage = window.localStorage.getItem("apsara-language");
    return savedLanguage && translations[savedLanguage] ? savedLanguage : "en";
  });

  useEffect(() => {
    const selected = languages.find((item) => item.code === language);
    document.documentElement.lang = language;
    document.documentElement.dir = selected?.dir || "ltr";
    window.localStorage.setItem("apsara-language", language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      languages,
      setLanguage: (nextLanguage) => {
        if (translations[nextLanguage]) {
          setLanguageState(nextLanguage);
        }
      },
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
